// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Widgets.VisitorInfo {
	
	
	public partial class Widget {
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl pName;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl pComment;
		
		protected System.Web.UI.WebControls.PlaceHolder phScript;
		
		protected System.Web.UI.WebControls.Literal ltWebsite;
	}
}
