// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Admin.ExtensionManager {
	
	
	public partial class UserControlsXmanagerExtensionsList {
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl lblErrorMsg;
		
		protected System.Web.UI.WebControls.GridView gridExtensionsList;
		
		protected System.Web.UI.WebControls.ImageButton btnPriorityUp;
		
		protected System.Web.UI.WebControls.ImageButton btnPriorityDwn;
		
		protected System.Web.UI.WebControls.Button btnRestart;
	}
}
