// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Admin.ExtensionManager {
	
	
	public partial class UserControlsXmanagerParameters {
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl ErrorMsg;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl InfoMsg;
		
		protected System.Web.UI.WebControls.PlaceHolder phAddForm;
		
		protected System.Web.UI.WebControls.Button btnAdd;
		
		protected System.Web.UI.WebControls.GridView grid;
	}
}
