//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogEngineWA.Widgets.ModeComments {
	
	
	public partial class Edit {
		
		protected System.Web.UI.WebControls.CheckBox cbShowComments;
		
		protected System.Web.UI.WebControls.TextBox txtSize;
		
		protected System.Web.UI.WebControls.TextBox txtNumber;
		
		protected System.Web.UI.WebControls.TextBox txtDays;
	}
}
