// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace BlogEngineWA.widgets.Twitter {
	
	
	public partial class Edit {
		
		protected System.Web.UI.WebControls.TextBox txtAccountUrl;
		
		protected System.Web.UI.WebControls.TextBox txtUrl;
		
		protected System.Web.UI.WebControls.TextBox txtTwits;
		
		protected System.Web.UI.WebControls.TextBox txtPolling;
		
		protected System.Web.UI.WebControls.TextBox txtFollowMe;
	}
}
