//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogEngineWA.widgets.Twitter {
	
	
	public partial class Edit {
		
		protected System.Web.UI.WebControls.TextBox txtAccountUrl;
		
		protected System.Web.UI.WebControls.TextBox txtUrl;
		
		protected System.Web.UI.WebControls.TextBox txtTwits;
		
		protected System.Web.UI.WebControls.TextBox txtPolling;
		
		protected System.Web.UI.WebControls.TextBox txtFollowMe;
	}
}
