//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogEngineWA.widgets.Twitter {
	
	
	public partial class Widget {
		
		protected System.Web.UI.WebControls.Repeater repItems;
		
		protected System.Web.UI.WebControls.Label lblDate;
		
		protected System.Web.UI.WebControls.Label lblItem;
		
		protected System.Web.UI.WebControls.HyperLink hlTwitterAccount;
	}
}
