// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace BlogEngineWA.widgets.Twitter {
	
	
	public partial class Widget {
		
		protected System.Web.UI.WebControls.Repeater repItems;
		
		protected System.Web.UI.WebControls.Label lblDate;
		
		protected System.Web.UI.WebControls.Label lblItem;
		
		protected System.Web.UI.WebControls.HyperLink hlTwitterAccount;
	}
}
