// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace BlogEngineWA.Admin.Pages {
	
	
	public partial class EditPage {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.Label lblVideoUpload;
		
		protected System.Web.UI.WebControls.FileUpload txtUploadVideo;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator txtUploadVideoValidator;
		
		protected System.Web.UI.WebControls.Button btnUploadVideo;
		
		protected System.Web.UI.WebControls.FileUpload txtUploadImage;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator2;
		
		protected System.Web.UI.WebControls.Button btnUploadImage;
		
		protected System.Web.UI.WebControls.FileUpload txtUploadFile;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator3;
		
		protected System.Web.UI.WebControls.Button btnUploadFile;
		
		protected System.Web.UI.WebControls.TextBox txtTitle;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator1;
		
		protected BlogEngineWA.Admin.HtmlEditor txtContent;
		
		protected System.Web.UI.WebControls.TextBox txtSlug;
		
		protected System.Web.UI.WebControls.TextBox txtDescription;
		
		protected System.Web.UI.WebControls.CheckBox cbPublished;
		
		protected System.Web.UI.WebControls.DropDownList ddlParent;
		
		protected System.Web.UI.WebControls.TextBox txtKeyword;
		
		protected System.Web.UI.WebControls.CheckBox cbFrontPage;
		
		protected System.Web.UI.WebControls.CheckBox cbShowInList;
	}
}
