// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace UserControls {
	
	
	public partial class CommentView {
		
		protected System.Web.UI.WebControls.PlaceHolder phComments;
		
		protected System.Web.UI.WebControls.PlaceHolder phTrckbacks;
		
		protected System.Web.UI.WebControls.PlaceHolder phAddComment;
		
		protected System.Web.UI.WebControls.HiddenField hiddenReplyTo;
		
		protected System.Web.UI.WebControls.Literal Literal1;
		
		protected System.Web.UI.WebControls.Literal Literal2;
		
		protected System.Web.UI.WebControls.TextBox txtEmail;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator2;
		
		protected System.Web.UI.WebControls.RegularExpressionValidator RegularExpressionValidator1;
		
		protected System.Web.UI.WebControls.TextBox txtWebsite;
		
		protected System.Web.UI.WebControls.RegularExpressionValidator RegularExpressionValidator2;
		
		protected System.Web.UI.WebControls.DropDownList ddlCountry;
		
		protected System.Web.UI.WebControls.Image imgFlag;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator3;
		
		protected System.Web.UI.WebControls.TextBox txtContent;
		
		protected BlogEngineWA.CustomCode.Extensions.Recaptcha.RecaptchaControl recaptcha;
		
		protected BlogEngineWA.CustomCode.Extensions.SimpleCaptcha.SimpleCaptchaControl simplecaptcha;
		
		protected System.Web.UI.WebControls.HiddenField hfCaptcha;
		
		protected System.Web.UI.WebControls.Label lbCommentsDisabled;
	}
}
