// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace UserControls {
	
	
	public partial class PostList {
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl posts;
		
		protected System.Web.UI.HtmlControls.HtmlAnchor hlPrev;
		
		protected System.Web.UI.HtmlControls.HtmlAnchor hlNext;
		
		protected BlogEngineWA.CustomCode.Controls.PostPager pager1;
	}
}
