// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace BlogEngineWA.Widgets.TagCloud {
	
	
	public partial class Edit {
		
		protected System.Web.UI.WebControls.DropDownList ddlMinimumPosts;
		
		protected System.Web.UI.WebControls.DropDownList ddlCloudSize;
	}
}
