//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogEngineWA.Widgets.TagCloud {
	
	
	public partial class WidgetsTagCloudWidget {
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl ulTags;
	}
}
