// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace BlogEngineWA {
	
	
	public partial class contact {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl divForm;
		
		protected System.Web.UI.WebControls.TextBox txtName;
		
		protected System.Web.UI.WebControls.TextBox txtEmail;
		
		protected System.Web.UI.WebControls.TextBox txtSubject;
		
		protected System.Web.UI.WebControls.TextBox txtMessage;
		
		protected System.Web.UI.WebControls.PlaceHolder phAttachment;
		
		protected System.Web.UI.WebControls.FileUpload txtAttachment;
		
		protected BlogEngineWA.CustomCode.Extensions.Recaptcha.RecaptchaControl recaptcha;
		
		protected System.Web.UI.WebControls.HiddenField hfCaptcha;
		
		protected System.Web.UI.WebControls.Button btnSend;
		
		protected System.Web.UI.WebControls.Label lblStatus;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl divThank;
	}
}
