// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace BlogEngineWA {
	
	
	public partial class error404 {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl divSearchEngine;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl divSearchResult;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl divExternalReferrer;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl divInternalReferrer;
		
		protected BlogEngineWA.CustomCode.Controls.SearchBox SearchBox2;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl divDirectHit;
		
		protected System.Web.UI.WebControls.PlaceHolder phSearchResult;
		
		protected BlogEngineWA.CustomCode.Controls.SearchBox SearchBox1;
	}
}
