//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogEngineWA {
	
	
	public partial class page {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl h1Title;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl divText;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl disqus_box;
	}
}
