// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace BlogEngineWA {
	
	
	public partial class page {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl h1Title;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl divText;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl disqus_box;
	}
}
