//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogEngineWA {
	
	
	public partial class post {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.PlaceHolder phCommentNotificationUnsubscription;
		
		protected System.Web.UI.WebControls.PlaceHolder phPostNavigation;
		
		protected System.Web.UI.WebControls.HyperLink hlPrev;
		
		protected System.Web.UI.WebControls.HyperLink hlNext;
		
		protected System.Web.UI.WebControls.PlaceHolder pwPost;
		
		protected System.Web.UI.WebControls.PlaceHolder phRDF;
		
		protected BlogEngineWA.CustomCode.Controls.RelatedPosts related;
		
		protected UserControls.CommentView CommentView1;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl disqus_box;
	}
}
