// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace BlogEngineWA {
	
	
	public partial class search {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl h1Headline;
		
		protected System.Web.UI.WebControls.Repeater rep;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl type;
		
		protected System.Web.UI.WebControls.PlaceHolder Paging;
	}
}
