// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace BlogEngineWA.Admin.Settings {
	
	
	public partial class Advanced {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected BlogEngineWA.Admin.Settings.Menu TabMenu;
		
		protected System.Web.UI.WebControls.CheckBox cbEnableTrackBackSend;
		
		protected System.Web.UI.WebControls.CheckBox cbEnableTrackBackReceive;
		
		protected System.Web.UI.WebControls.CheckBox cbEnablePingBackSend;
		
		protected System.Web.UI.WebControls.CheckBox cbEnablePingBackReceive;
		
		protected System.Web.UI.WebControls.RadioButtonList rblWwwSubdomain;
		
		protected System.Web.UI.WebControls.CheckBox cbEnableCompression;
		
		protected System.Web.UI.WebControls.CheckBox cbRemoveWhitespaceInStyleSheets;
		
		protected System.Web.UI.WebControls.CheckBox cbCompressWebResource;
		
		protected System.Web.UI.WebControls.CheckBox cbEnableOpenSearch;
		
		protected System.Web.UI.WebControls.CheckBox cbRequireSslForMetaWeblogApi;
		
		protected System.Web.UI.WebControls.CheckBox cbEnableErrorLogging;
		
		protected System.Web.UI.WebControls.TextBox txtRemoteTimeout;
		
		protected System.Web.UI.WebControls.TextBox txtRemoteMaxFileSize;
		
		protected System.Web.UI.WebControls.CheckBox cbAllowRemoteFileDownloads;
	}
}
