// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace BlogEngineWA.Admin.Settings {
	
	
	public partial class Settings {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected BlogEngineWA.Admin.Settings.Menu TabMenu1;
		
		protected System.Web.UI.WebControls.DropDownList ddlCloseComments;
		
		protected System.Web.UI.WebControls.CheckBox cbEnableComments;
		
		protected System.Web.UI.WebControls.CheckBox cbEnableCommentsModeration;
		
		protected System.Web.UI.WebControls.CheckBox cbEnableCommentNesting;
		
		protected System.Web.UI.WebControls.CheckBox cbEnableCoComment;
		
		protected System.Web.UI.WebControls.RadioButtonList rblAvatar;
		
		protected System.Web.UI.WebControls.DropDownList ddlCommentsPerPage;
		
		protected System.Web.UI.WebControls.CheckBox cbEnableCountryInComments;
		
		protected System.Web.UI.WebControls.CheckBox cbShowLivePreview;
		
		protected System.Web.UI.WebControls.CheckBox cbShowPingBacks;
		
		protected System.Web.UI.WebControls.CheckBox cbEnableDisqus;
		
		protected System.Web.UI.WebControls.TextBox txtDisqusName;
		
		protected System.Web.UI.WebControls.CheckBox cbDisqusDevMode;
		
		protected System.Web.UI.WebControls.CheckBox cbDisqusAddToPages;
		
		protected System.Web.UI.WebControls.Button btnSave;
	}
}
