// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace BlogEngineWA.Admin.Settings {
	
	
	public partial class Email {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected BlogEngineWA.Admin.Settings.Menu TabMenu;
		
		protected System.Web.UI.WebControls.TextBox txtEmail;
		
		protected System.Web.UI.WebControls.TextBox txtSmtpServer;
		
		protected System.Web.UI.WebControls.TextBox txtSmtpServerPort;
		
		protected System.Web.UI.WebControls.TextBox txtSmtpUsername;
		
		protected System.Web.UI.WebControls.TextBox txtSmtpPassword;
		
		protected System.Web.UI.WebControls.TextBox txtEmailSubjectPrefix;
		
		protected System.Web.UI.WebControls.CheckBox cbEnableSsl;
		
		protected System.Web.UI.WebControls.CheckBox cbComments;
		
		protected System.Web.UI.WebControls.Label lbSmtpStatus;
	}
}
