// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace BlogEngineWA.Admin.Settings {
	
	
	public partial class Feed {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected BlogEngineWA.Admin.Settings.Menu TabMenu;
		
		protected System.Web.UI.WebControls.TextBox txtDublinCoreCreator;
		
		protected System.Web.UI.WebControls.TextBox txtEmail;
		
		protected System.Web.UI.WebControls.TextBox txtBlogChannelBLink;
		
		protected System.Web.UI.WebControls.TextBox txtAlternateFeedUrl;
		
		protected System.Web.UI.WebControls.DropDownList ddlSyndicationFormat;
		
		protected System.Web.UI.WebControls.TextBox txtDublinCoreLanguage;
		
		protected System.Web.UI.WebControls.TextBox txtPostsPerFeed;
		
		protected System.Web.UI.WebControls.TextBox txtGeocodingLatitude;
		
		protected System.Web.UI.WebControls.TextBox txtGeocodingLongitude;
		
		protected System.Web.UI.WebControls.CheckBox cbEnableEnclosures;
	}
}
