// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace BlogEngineWA.Admin.Settings {
	
	
	public partial class Main {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected BlogEngineWA.Admin.Settings.Menu TabMenu;
		
		protected System.Web.UI.WebControls.TextBox txtName;
		
		protected System.Web.UI.WebControls.TextBox txtDescription;
		
		protected System.Web.UI.WebControls.DropDownList ddlTheme;
		
		protected System.Web.UI.WebControls.DropDownList ddlMobileTheme;
		
		protected System.Web.UI.WebControls.TextBox txtThemeCookieName;
		
		protected System.Web.UI.WebControls.DropDownList ddlCulture;
		
		protected System.Web.UI.WebControls.TextBox txtTimeZone;
		
		protected System.Web.UI.WebControls.TextBox txtPostsPerPage;
		
		protected System.Web.UI.WebControls.CheckBox cbShowDescriptionInPostList;
		
		protected System.Web.UI.WebControls.TextBox txtDescriptionCharacters;
		
		protected System.Web.UI.WebControls.CheckBox cbShowDescriptionInPostListForPostsByTagOrCategory;
		
		protected System.Web.UI.WebControls.TextBox txtDescriptionCharactersForPostsByTagOrCategory;
		
		protected System.Web.UI.WebControls.CheckBox cbShowRelatedPosts;
		
		protected System.Web.UI.WebControls.CheckBox cbShowPostNavigation;
		
		protected System.Web.UI.WebControls.CheckBox cbUseBlogNameInPageTitles;
		
		protected System.Web.UI.WebControls.CheckBox cbEnableRating;
		
		protected System.Web.UI.WebControls.CheckBox cbTimeStampPostLinks;
		
		protected System.Web.UI.WebControls.CheckBox cbEnablePasswordReset;
		
		protected System.Web.UI.WebControls.CheckBox cbEnableSelfRegistration;
		
		protected System.Web.UI.WebControls.DropDownList ddlSelfRegistrationInitialRole;
	}
}
