// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace BlogEngineWA.Admin.Settings {
	
	
	public partial class admin_Pages_PingServices {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected BlogEngineWA.Admin.Settings.Menu TabMenu1;
		
		protected System.Web.UI.WebControls.TextBox txtNewCategory;
		
		protected System.Web.UI.WebControls.Button btnAdd;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator1;
		
		protected System.Web.UI.WebControls.GridView grid;
		
		protected System.Web.UI.WebControls.TextBox txtName;
	}
}
