// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace BlogEngineWA.Admin.Settings {
	
	
	public partial class Rules {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected BlogEngineWA.Admin.Settings.Menu TabMenu1;
		
		protected System.Web.UI.WebControls.DropDownList ddWhiteListCount;
		
		protected System.Web.UI.WebControls.CheckBox cbAddIpToWhitelistFilterOnApproval;
		
		protected System.Web.UI.WebControls.DropDownList ddBlackListCount;
		
		protected System.Web.UI.WebControls.CheckBox cbTrustAuthenticated;
		
		protected System.Web.UI.WebControls.CheckBox cbBlockOnDelete;
		
		protected System.Web.UI.WebControls.CheckBox cbAddIpToBlacklistFilterOnRejection;
		
		protected System.Web.UI.WebControls.DropDownList ddAction;
		
		protected System.Web.UI.WebControls.DropDownList ddSubject;
		
		protected System.Web.UI.WebControls.DropDownList ddOperator;
		
		protected System.Web.UI.WebControls.TextBox txtFilter;
		
		protected System.Web.UI.WebControls.Button btnAddFilter;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl FilterValidation;
		
		protected System.Web.UI.WebControls.GridView gridFilters;
		
		protected System.Web.UI.WebControls.ImageButton btnDelete;
		
		protected System.Web.UI.WebControls.CheckBox cbReportMistakes;
		
		protected System.Web.UI.WebControls.Button btnSave;
	}
}
