// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace BlogEngineWA.Widgets.PageList {
	
	
	public partial class Widget {
		
		protected BlogEngineWA.CustomCode.Controls.PageList PageList1;
	}
}
