// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace BlogEngineWA.Widgets.CategoryList {
	
	
	public partial class WidgetsCategoriesEdit {
		
		protected System.Web.UI.WebControls.CheckBox cbShowRssIcon;
		
		protected System.Web.UI.WebControls.CheckBox cbShowPostCount;
	}
}
