// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace BlogEngineWA.Admin.Posts {
	
	
	public partial class AddEntry {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.Label lblVideoUpload;
		
		protected System.Web.UI.WebControls.FileUpload txtUploadVideo;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator txtUploadVideoValidator;
		
		protected System.Web.UI.WebControls.Button btnUploadVideo;
		
		protected System.Web.UI.WebControls.Label lblFileUpload;
		
		protected System.Web.UI.WebControls.FileUpload txtUploadImage;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator3;
		
		protected System.Web.UI.WebControls.Button btnUploadImage;
		
		protected System.Web.UI.WebControls.Label Label1;
		
		protected System.Web.UI.WebControls.FileUpload txtUploadFile;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator4;
		
		protected System.Web.UI.WebControls.Button btnUploadFile;
		
		protected System.Web.UI.WebControls.TextBox txtTitle;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator1;
		
		protected System.Web.UI.WebControls.CheckBox cbUseRaw;
		
		protected BlogEngineWA.Admin.HtmlEditor txtContent;
		
		protected System.Web.UI.WebControls.TextBox txtRawContent;
		
		protected System.Web.UI.WebControls.Label Label2;
		
		protected System.Web.UI.WebControls.TextBox txtSlug;
		
		protected System.Web.UI.WebControls.Label Label3;
		
		protected System.Web.UI.WebControls.TextBox txtDescription;
		
		protected System.Web.UI.WebControls.CheckBox cbEnableComments;
		
		protected System.Web.UI.WebControls.CheckBox cbPublish;
		
		protected System.Web.UI.WebControls.DropDownList ddlAuthor;
		
		protected System.Web.UI.WebControls.TextBox txtDate;
		
		protected System.Web.UI.WebControls.TextBox txtTime;
		
		protected System.Web.UI.WebControls.RegularExpressionValidator RegularExpressionValidator1;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator2;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl cblCategories;
		
		protected System.Web.UI.WebControls.TextBox txtCategory;
		
		protected System.Web.UI.WebControls.Button btnCategory;
		
		protected System.Web.UI.WebControls.CustomValidator valExist;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator5;
		
		protected System.Web.UI.WebControls.TextBox txtTags;
		
		protected System.Web.UI.WebControls.PlaceHolder phTags;
	}
}
