// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace BlogEngineWA.Admin.Posts {
	
	
	public partial class admin_Pages_Categories {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected BlogEngineWA.Admin.Posts.Menu TabMenu;
		
		protected System.Web.UI.WebControls.Label lblNewCategory;
		
		protected System.Web.UI.WebControls.TextBox txtNewCategory;
		
		protected System.Web.UI.WebControls.CustomValidator valExist;
		
		protected System.Web.UI.WebControls.Label lblNewNewDescription;
		
		protected System.Web.UI.WebControls.TextBox txtNewNewDescription;
		
		protected System.Web.UI.WebControls.Label lblNewParent;
		
		protected System.Web.UI.WebControls.DropDownList ddlNewParent;
		
		protected System.Web.UI.WebControls.Button btnAdd;
		
		protected System.Web.UI.WebControls.GridView grid;
		
		protected System.Web.UI.WebControls.TextBox txtTitle;
		
		protected System.Web.UI.WebControls.TextBox txtDescription;
		
		protected System.Web.UI.WebControls.DropDownList ddlParent;
	}
}
