// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace BlogEngineWA.Admin.Widgets {
	
	
	public partial class admin_Pages_blogroll {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected BlogEngineWA.Admin.Widgets.Menu TabMenu;
		
		protected System.Web.UI.WebControls.DropDownList ddlVisiblePosts;
		
		protected System.Web.UI.WebControls.TextBox txtMaxLength;
		
		protected System.Web.UI.WebControls.CompareValidator CompareValidator1;
		
		protected System.Web.UI.WebControls.TextBox txtUpdateFrequency;
		
		protected System.Web.UI.WebControls.CompareValidator CompareValidator2;
		
		protected System.Web.UI.WebControls.Button btnSaveSettings;
		
		protected System.Web.UI.WebControls.TextBox txtTitle;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator1;
		
		protected System.Web.UI.WebControls.TextBox txtDescription;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator2;
		
		protected System.Web.UI.WebControls.TextBox txtWebUrl;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator3;
		
		protected System.Web.UI.WebControls.CustomValidator CustomValidator1;
		
		protected System.Web.UI.WebControls.TextBox txtFeedUrl;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator4;
		
		protected System.Web.UI.WebControls.CustomValidator CustomValidator2;
		
		protected System.Web.UI.WebControls.CheckBoxList cblXfn;
		
		protected System.Web.UI.WebControls.Button btnSave;
		
		protected System.Web.UI.WebControls.GridView grid;
		
		protected System.Web.UI.WebControls.HyperLink feedLink;
		
		protected System.Web.UI.WebControls.HyperLink HyperLink1;
		
		protected System.Web.UI.WebControls.Literal Literal1;
		
		protected System.Web.UI.WebControls.ImageButton ibMoveUp;
		
		protected System.Web.UI.WebControls.ImageButton ibMoveDown;
	}
}
