// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace BlogEngineWA.Admin.Widgets {
	
	
	public partial class Controls {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected BlogEngineWA.Admin.Widgets.Menu TabMenu;
		
		protected System.Web.UI.WebControls.TextBox txtNumberOfPosts;
		
		protected System.Web.UI.WebControls.CheckBox cbDisplayComments;
		
		protected System.Web.UI.WebControls.CheckBox cbDisplayRating;
		
		protected System.Web.UI.WebControls.TextBox txtNumberOfComments;
		
		protected System.Web.UI.WebControls.TextBox txtSearchButtonText;
		
		protected System.Web.UI.WebControls.TextBox txtDefaultSearchText;
		
		protected System.Web.UI.WebControls.TextBox txtCommentLabelText;
		
		protected System.Web.UI.WebControls.CheckBox cbEnableCommentSearch;
		
		protected System.Web.UI.WebControls.TextBox txtFormMessage;
		
		protected System.Web.UI.WebControls.TextBox txtThankMessage;
		
		protected System.Web.UI.WebControls.CheckBox cbEnableAttachments;
		
		protected System.Web.UI.WebControls.CheckBox cbEnableRecaptcha;
		
		protected System.Web.UI.WebControls.Button btnSave;
	}
}
