//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



public partial class IndigoSite {
	
	protected System.Web.UI.HtmlControls.HtmlForm Form1;
	
	protected BlogEngineWA.CustomCode.Controls.SearchOnSearch SearchOnSearch1;
	
	protected System.Web.UI.WebControls.ContentPlaceHolder cphBody;
}
