// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace BlogEngineWA.Admin.Tracking {
	
	
	public partial class Referrers {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected BlogEngineWA.Admin.Tracking.Menu TabMenu;
		
		protected System.Web.UI.WebControls.CheckBox cbEnableReferrers;
		
		protected System.Web.UI.WebControls.TextBox txtNumberOfDays;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl infoPanel;
		
		protected System.Web.UI.WebControls.Panel referrersPanel;
		
		protected System.Web.UI.WebControls.DropDownList ddlDays;
		
		protected System.Web.UI.WebControls.GridView grid;
		
		protected System.Web.UI.WebControls.Panel possibleSmapPanel;
		
		protected System.Web.UI.WebControls.GridView spamGrid;
	}
}
