// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace BlogEngineWA.Admin {
	
	
	public partial class AdminMasterPage {
		
		protected System.Web.UI.HtmlControls.HtmlHead Head1;
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl AdminStatus;
		
		protected System.Web.UI.WebControls.LoginStatus LoginStatus1;
		
		protected BlogEngineWA.Admin.Menu Menu1;
		
		protected System.Web.UI.WebControls.PlaceHolder phRecycleBin;
		
		protected System.Web.UI.WebControls.ContentPlaceHolder cphAdmin;
		
		protected System.Web.UI.HtmlControls.HtmlAnchor donate;
	}
}
