// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace BlogEngineWA.Admin {
	
	
	public partial class WidgetEditor {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.TextBox txtTitle;
		
		protected System.Web.UI.WebControls.CheckBox cbShowTitle;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl phEdit;
		
		protected System.Web.UI.WebControls.Button btnSave;
	}
}
