//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogEngineWA.Account {
	
	
	public partial class AccountMasterPage {
		
		protected System.Web.UI.HtmlControls.HtmlHead Head1;
		
		protected System.Web.UI.WebControls.ContentPlaceHolder HeadContent;
		
		protected System.Web.UI.HtmlControls.HtmlForm Form1;
		
		protected System.Web.UI.HtmlControls.HtmlAnchor HeadLoingHome;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl AdminStatus;
		
		protected System.Web.UI.WebControls.ContentPlaceHolder MainContent;
	}
}
