// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace BlogEngineWA.Account {
	
	
	public partial class Login {
		
		protected System.Web.UI.WebControls.Content HeaderContent;
		
		protected System.Web.UI.WebControls.Content BodyContent;
		
		protected System.Web.UI.WebControls.Login LoginUser;
		
		protected System.Web.UI.WebControls.Label lblTitle;
		
		protected System.Web.UI.WebControls.Label UserNameLabel;
		
		protected System.Web.UI.WebControls.TextBox UserName;
		
		protected System.Web.UI.WebControls.Label PasswordLabel;
		
		protected System.Web.UI.WebControls.TextBox Password;
		
		protected System.Web.UI.WebControls.CheckBox RememberMe;
		
		protected System.Web.UI.WebControls.Label RememberMeLabel;
		
		protected System.Web.UI.WebControls.Button LoginButton;
		
		protected System.Web.UI.WebControls.PlaceHolder phResetPassword;
		
		protected System.Web.UI.WebControls.HyperLink linkForgotPassword;
		
		protected System.Web.UI.WebControls.HyperLink RegisterHyperLink;
		
		public new BlogEngineWA.Account.AccountMasterPage Master {
			get {
				return ((BlogEngineWA.Account.AccountMasterPage)(base.Master));
			}
		}
	}
}
