//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogEngineWA.Account {
	
	
	public partial class PasswordRetrieval {
		
		protected System.Web.UI.WebControls.Content HeaderContent;
		
		protected System.Web.UI.WebControls.Content BodyContent;
		
		protected System.Web.UI.WebControls.Label EmailLabel;
		
		protected System.Web.UI.WebControls.TextBox txtEmail;
		
		protected System.Web.UI.WebControls.Button LoginButton;
		
		public new BlogEngineWA.Account.AccountMasterPage Master {
			get {
				return ((BlogEngineWA.Account.AccountMasterPage)(base.Master));
			}
		}
	}
}
